### ISSUE TITLE
Identifying other similar pages where an edit is necessary (page title)

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto-validator#1]
On certain pages (especially during menu choices in ch4), I would like to add a <br> to the page title, so that the information ([4 days left], etc.) appears on a new line. Is there any way to identify other pages where I need to make this edit, once I've done it on one page? (e.g. I could search "[...days left]" and all the pages where this is in the title would appear, so that I could work through editing them manually)

**Comment by interrogator** [comment]
The best way to do this is using Atom. You can use `Find -> Find in project`, and then if you want, limit the search to only particular directories using the bottom field on the Find bar that pops up.

You could then search for 'days left' and all the files containing this will be shown. If you need more search flexibility, you can turn on regular expressions and do something like `[0-9]+ days? left` to match `10 days left`, `1 day left`, `0 days left`, etc.

**Comment by interrogator** [comment]
Actually, even easier is to right click the folder in the sidebar, and do 'Search in folder'.
