### ISSUE TITLE
Identifying similar pages where an edit is necessary (imageComponent)

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto-validator#2]
If I decide that I need to redesign a page in order to make, say, a textExercise easier, is there any advanced search function where I can look for all page folders which contain both an imageComponent.json page *and* a textExercise.json page, so that I would be able to have a list of which pages need to be redesigned? (Or similarly other combinations: textExercise + dateExercise + dialog, for example)

**Comment by interrogator** [comment]
Yes. This has now been implemented as `marufind`. The documentation is on the main page of this repository. Let me know if you need the tool to do more.
